### ISSUE TITLE
Unable to make new submissions on the EvalAI site

### ISSUE THREAD

**Issue by edbeeching** [facebookresearch/habitat-challenge#7] opened 2019-04-17 08:33 UTC
For the past two days I have been unable to make new submissions to the EvalAI site. I even re-cloned the repo, cleared my docker caches and tried to resubmit the random baseline agent with no success.

Previously I was able to make submissions, so I am wondering if the issue is on the EvalAI platform?

I created a topic on their forum but I have had no response yet, if you are able to confirm that the platform is still working that would be much appreciated. (for example by submitting a random agent)

**Comment by abhiskk** [comment] 2019-04-17 16:29
Hi @edbeeching, sorry for the problems, I will get back to you soon, this most likely is an issue on the backend.

**Comment by abhiskk** [comment] 2019-04-21 22:06
Hi @edbeeching, I tested your latest submission and I can confirm that the issue is not on the backend side now. Do you have any specific submission id that you want to test, I would suggest making a resubmission now and checking if your submission runs successfully.

**Comment by edbeeching** [comment] 2019-04-30 08:14
Hi @abhiskk, sorry for the slow reply, I was out of the office. 
Thank you for testing this. I see my most recent submission was working. I tried again this morning and unfortunately I am getting the same error as before. Would you be able to check if the issue is the backend?

**Comment by abhiskk** [comment] 2019-05-01 00:48
@edbeeching , I re-evaluated your recent submission and it was evaluated successfully, let me know if you still face troubles.

**Comment by edbeeching** [comment] 2019-05-09 11:01
@abhiskk . Thank you. I have been able to  make new submissions. However I noticed that some submissions appear to succeed on one phase and fail on others. The stderr and stdout are both empty so I am not sure of the cause. It is odd as it is not as if they timeout as my recent RGB submission succeeded on the test-std phase but failed on the mini-val. I guess the best course of action would be to make new submissions?

**Comment by abhiskk** [comment] 2019-05-09 14:17
Hi @edbeeching, I am seeing some non-deterministic behavior especially with download of dockers, we will evaluate your submissions again and I will get back to you with the results soon.

**Comment by abhiskk** [comment] 2019-05-09 18:54
@edbeeching all your submissions have been successfully evaluated now. Let me know if you face more issues.

**Comment by jozhang97** [comment] 2019-05-09 23:06
Hi,
I'm having trouble submitting to evalAI but things run fine locally (I get an SPL number at the end). 
The results json, stdout, and stderr logs are empty. What should my course of action be?

In general, i was wondering what the remote server is looking for? To me, it seems like it wants a `/submission.sh` file that in the end somewhere calls `challenge.submit(agent)` 

Thanks in advance!

**Comment by abhiskk** [comment] 2019-05-09 23:30
Hi @jozhang97 , yes we are looking into this, we are facing problems with our docker registry, I will get back to you with more updates. If it runs successfully on your end then it should be successful on our end also. Will get back soon.

**Comment by abhiskk** [comment] 2019-05-10 00:29
@jozhang97 your docker image is quite large 23GB, is it possible to submit a smaller sized image, something around 10GB. Are you including the Gibson dataset also in your docker container? You don't need to include that.

**Comment by jozhang97** [comment] 2019-05-10 00:37
@abhiskk  Thanks for your fast response. 

Sure smaller docker should be no problem. I'll create another submission

**Comment by jozhang97** [comment] 2019-05-10 02:15
@abhiskk worked like a charm for val_mini. Thanks!

**Comment by jozhang97** [comment] 2019-05-10 04:09
Hi @abhiskk 
Sorry to bother but my submission to `test-std` failed. Is this a timeout issue (my agent is not making the 30minute cutoff) or something different?

**Comment by edbeeching** [comment] 2019-05-10 14:07
@abhiskk sorry to bother you again but I have two further submissions on the RGB mini-val and test-std track that have failed, the image worked on my machine. Thanks again for any assistance.

**Comment by abhiskk** [comment] 2019-05-10 15:35
@jozhang97 @edbeeching we are re-evaluating your submissions, will get back here soon once the results are updated.

**Comment by abhiskk** [comment] 2019-05-10 22:45
Hi, most of the submissions have been evaluated successfully, @jozhang97 for one of your submission that failed it was missing a `submission.sh` file. @edbeeching one of your submission which is failed will be re-evaluated again, will get back if there is any specific reason for it crashing.

**Comment by jozhang97** [comment] 2019-05-15 17:51
@abhiskk I made another submission yesterday to test-std and minival both of which failed. I was wondering if you could help me figure out whats happening. Thanks so much

**Comment by abhiskk** [comment] 2019-05-16 16:24
Hi @jozhang97 , your submission was evaluated and the results were updated, we were resolving an issue on our side which lead to the crashed submission.

**Comment by jozhang97** [comment] 2019-05-17 20:19
@abhiskk Thanks for your response. I did see the ones from above working but new ones that I submitted have failed. Would this be due to the same issue?

**Comment by abhiskk** [comment] 2019-05-17 21:20
Hi @jozhang97 , your submission is taking more than 30 mins to run, do you have an estimate of how long it will take for your submission to finish on 1000 episodes, I will adjust the timelimit accordingly.

**Comment by jozhang97** [comment] 2019-05-17 23:39
Hi @abhiskk! Thanks for your response. hmmm It takes ~30 (31, 27, 34) minutes on my machine to run 900 episodes. 
My hardware knowledge is very limited. But I do know the following: You guys are using Tesla K80 GPU (12 GB Memory), 4 CPU cores, and 61 GB RAM while I'm running locally on GeForce GTX 1080, 6 CPU cores, 32 GB RAM.

**Comment by mathfac** [comment] 2020-03-23 18:29
Closing the issue as very old one. Feel free to reopen if needed.

**Closed by mathfac** 2020-03-23 18:29 UTC
